import { useState, useEffect } from 'react';
import './Cats.css';

const ImageRotator = () => {
  const images = [
    "%2424.50.png",
    "Ah_So_Cat.png",
    "AI_Scandal.png",
    "Angelina.jpg",
    "Aoba.png",
    "Apple_Cat.jpg",
    "Armoured_Cat.png",
    "Arthur.jpg",
    "Artyom.png",
    "Axle_the_Kitty.png",
    "Babem.png",
    "Baby_Kiwi_Kitten.png",
    "Bag.png",
    "Baskit_Cat.png",
    "Bathder.png",
    "Bat_Cat.png",
    "Bb.png",
    "Belize.png",
    "Bentley.png",
    "Bernard.jpg",
    "Bert.png",
    "Better_Goofus.png",
    "Big_Billy.png",
    "Big_Poo.png",
    "Big_Tom.png",
    "Billy.png",
    "Bingulius_fr_not_brainus.png",
    "Bingus.png",
    "Bleemk.png",
    "Bleg.jpg",
    "Bob_New.png",
    "Boingus.png",
    "Bongo.jpg",
    "Bounty_hunter_cat_.png",
    "Brainless.png",
    "Brunnincast.png",
    "Bubble_Cat.png",
    "Buck.jpg",
    "Buffed_Kitty.png",
    "Buh.png",
    "Bungus.png",
    "Cala.png",
    "Canela_%28finally%29.jpg",
    "Canny_Cat.png",
    "Carlos.png",
    "CatMine.png",
    "Cheeseburger.png",
    "Chipi_Chipi_Chapa_Chapa_Cat.png",
    "Clown_Uprising_Clown.png",
    "Cokey_Cola.png",
    "Confusion_of_a_Cat%2C_pretty_silly_tho.png",
    "Corruptor.png",
    "CowboyCat.png",
    "Criminal_Cat.png",
    "Deksy.png",
    "Demetrus_P._Dinklebottom.png",
    "DemonCat.jpg",
    "Demonic_Little_Grey_Cat.png",
    "Die.png",
    "Dietzen_D._Dinklebottom.png",
    "Dimden.png",
    "Dmitri.png",
    "Doobis.png",
    "Drazy_Cat.png",
    "Drefis.png",
    "Dresstoimpress.png",
    "Dr_Pebba.png",
    "Dr_Peppy.png",
    "E._Scrunk.png",
    "Edward.png",
    "Eepeer_%28Endless_Eeps%29.png",
    "El_Gato.png",
    "Ernesto.png",
    "Ethel_the_cat_with_bg.png",
    "Evil_Cat.png",
    "Eyebrow.png",
    "Fanter.png",
    "Ferret.jpg",
    "Floppa.png",
    "Florbi.png",
    "Flower_Cat.png",
    "Food_Center_Leakage.png",
    "Fouet.png",
    "Future_Kitty.png",
    "Gakster.png",
    "Gamer_Kitten.png",
    "Garbo_Cat.jpg",
    "Geeble.png",
    "Gentleman.png",
    "George.jpg",
    "Glinkert.png",
    "Glombie.png",
    "Glooberousing.png",
    "Glooble.jpg",
    "Glorpo.png",
    "Glumbus.png",
    "Glumby.jpg",
    "Glungus_%281%29.png",
    "Gnapy.png",
    "GnarpGnaplians.png",
    "Goga_Cat.png",
    "Goob.png",
    "Goober_the_Eighth.png",
    "Goober_the_fifth.png",
    "Goober_the_Fourth.png",
    "Goober_the_Ninth.png",
    "Goober_the_Second.png",
    "Goober_the_Sixth.png",
    "Goober_the_Tenth.png",
    "Goober_the_Third.png",
    "Gordon_Meowsay.png",
    "Grinwatcher.png",
    "Grumpy_Cat.png",
    "Guh.png",
    "Gusic.png",
    "Gwumbo_leaked_photo.jpg",
    "Halo.png",
    "Happy_Cat.png",
    "Harold.png",
    "Haru.png",
    "Herbert.jpg",
    "Him.png",
    "Hu.jpg",
    "Idek.png",
    "Inner_Demon_Luna.png",
    "Jinx.png",
    "Jocelin.png",
    "Johntabion.jpg",
    "Jose.png",
    "Juice_Cat.jpg",
    "KFC_Bucket_Cat.png",
    "Kitler.png",
    "KittyOh.png",
    "Kiw.png",
    "Kyky.png",
    "Larry.jpg",
    "Leonard.jpg",
    "Longcat.png",
    "Ludwig.png",
    "Luna.png",
    "Luna4.png",
    "Maxwell.png",
    "Meevin.png",
    "Melon_Cat_Species_1.png",
    "Milly.png",
    "Mimsie.png",
    "Molly.png",
    "Monsert.png",
    "Mr._Despair.png",
    "Mr._Fresh.png",
    "Mr._Poo.png",
    "Mrs_Pringleton_my_beloved_-%29.png",
    "Neeble.png",
    "Nilbert.png",
    "Noopy.png",
    "Ohmygos.png",
    "Oliver.jpg",
    "Oui_oui.png",
    "PankoStare.png",
    "Pepsie.png",
    "Photosynthesizing.png",
    "Plimpus.png",
    "Ploobie.png",
    "Pluh.jpg",
    "Pobis.png",
    "Poncky.png",
    "Potato.png",
    "Prongles.png",
    "Pusha.jpg",
    "Quetzkol_The_Incomprehensible_Deity.png",
    "Q_The_Cat.png",
    "Racist_Cat.png",
    "Radio_Cat.jpg",
    "Ramses.jpg",
    "Richer_Motion.png",
    "Roobeer.png",
    "Sam.png",
    "Samuraicat.png",
    "Scaredy_Cat.png",
    "Selfie.png",
    "ShadowLurker.jpg",
    "Shark.png",
    "Sheriff_Paw.jpg",
    "SHINY_Cuh.png",
    "Shoob.png",
    "Silly_Willy_Kitty.jpg",
    "Sir_Meows.png",
    "Skeletus.jpg",
    "Slorphus.png",
    "Sneezy_Cat.png",
    "Snuggles.jpg",
    "Sora_UwU.png",
    "Sox.jpg",
    "So_Silly.png",
    "Spirte.png",
    "Strawberry_Cat.png",
    "Study_Cat.png",
    "Supreme_Giant_Cat.png",
    "Tater_tot_.jpg",
    "Terrorist_Cat.jpg",
    "The_Beast.png",
    "The_Eeper.png",
    "The_Fry_Stealer.jpg",
    "The_Meeper.png",
    "The_Mimir.png",
    "The_One_Of_Them.png",
    "The_Pizzer.png",
    "The_Sitter.png",
    "The_Squeeker.png",
    "The_Squeeper.png",
    "The_Teefer.png",
    "Thing_i_made_on_photoshop.png"
    ];

  const [currentIndex, setCurrentIndex] = useState(0);

  useEffect(() => {
    const interval = setInterval(() => {
      setCurrentIndex(prevIndex => (prevIndex + 1) % images.length);
    }, 3000);

    return () => clearInterval(interval);
  }, []);

  return <img src={"/cats/" + images[currentIndex]} alt="cat." style={{
            width: '100%',
            height: '100%',
            objectFit: 'contain',
            boxShadow: 'rgba(0, 0, 0, 0.25) 0px 0px 10px',
            borderRadius: '20px'
          }}
        />;
};

function Cats() {
    return (
        <>
          <h1 className='title'>cats</h1>
          <hr style={{
              width: '100%',
              height: '1px',
              border: 'none',
              backgroundColor: '#939393'
            }} />
          <div style={{
            maxWidth: '90%',    
            overflow: 'hidden',
            position: 'relative',
          }}>
            <ImageRotator />
          </div>
        </>
    )
}

export default Cats;